name: 🎮 Manual Test Execution

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test Suite to Run'
        required: true
        type: choice
        default: 'smoke'
        options:
          - smoke
          - critical
          - regression
          - login
          - products
          - cart
          - checkout
          - e2e
          - negative
          - validation
          - sorting
          - navigation
      browser:
        description: 'Browser'
        required: true
        type: choice
        default: 'chromium'
        options:
          - chromium
          - firefox
          - webkit
          - all

jobs:
  manual-tests:
    name: Run ${{ inputs.test_suite }} tests on ${{ inputs.browser }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 📦 Install dependencies
        run: npm ci
      
      - name: 🎭 Install Playwright
        run: npx playwright install --with-deps
      
      - name: 🧪 Run Tests
        run: |
          if [ "${{ inputs.browser }}" == "all" ]; then
            npm run test:${{ inputs.test_suite }}
          else
            npx playwright test --grep @${{ inputs.test_suite }} --project=${{ inputs.browser }}
          fi
      
      - name: 📊 Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: manual-test-report-${{ inputs.test_suite }}-${{ inputs.browser }}
          path: playwright-report/
          retention-days: 7
      
      - name: 📈 Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ inputs.test_suite }}-${{ inputs.browser }}
          path: test-results/
          retention-days: 7